window:
  padding:
    x: 5
    y: 5

font:
  normal:
    family: Fira Code Retina
    style: Regular

  size: 14.0

# --| Solarized Light |---------------------------------------------------------
colors:
  primary:
    background: '0xfdf6e3'
    foreground: '0x586e75'

  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  cursor:
    text: CellForeground
    cursor: '0xeee8d5'

  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  vi_mode_cursor:
    text: CellForeground
    cursor: '0xeee8d5'

  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  selection:
    text: CellForeground
    background: '0xeee8d5'

  normal:
    black:   '0x073642'
    red:     '0xdc322f'
    green:   '0x859900'
    yellow:  '0xb58900'
    blue:    '0x268bd2'
    magenta: '0xd33682'
    cyan:    '0x2aa198'
    white:   '0xeee8d5'

  bright:
    black:   '0x002b36'
    red:     '0xcb4b16'
    green:   '0x586e75'
    yellow:  '0x657b83'
    blue:    '0x839496'
    magenta: '0x6c71c4'
    cyan:    '0x93a1a1'
    white:   '0xfdf6e3'
